application: strandrecycled
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /purgemain
  script: recycled-app.application
  login: admin
- url: /stylesheets
  static_dir: stylesheets
- url: /src
  static_dir: src
- url: /.*
  script: recycled-app.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest